### ISSUE TITLE
Not sure what happened, but there is an error

### ISSUE THREAD

**Issue by FortniteFevers** [LiBa001/disputils#38]
Ignoring exception in command help:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 144, in help
    from disputils import BotEmbedPaginator
  File "/usr/local/lib/python3.6/dist-packages/disputils/__init__.py", line 1, in <module>
    from .pagination import EmbedPaginator, BotEmbedPaginator, ControlEmojis
  File "/usr/local/lib/python3.6/dist-packages/disputils/pagination.py", line 13, in <module>
    defaults=("⏮", "◀", "▶", "⏭", "⏹"),
TypeError: namedtuple() got an unexpected keyword argument 'defaults'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: namedtuple() got an unexpected keyword argument 'defaults'

**Comment by LiBa001** [comment]
Oh, I just realized that the 'defaults' argument was only added in Python 3.7 and you are probably still on 3.6.
Is it possible for you to upgrade your Python version? That'd be the easiest fix to that issue.

**Comment by FortniteFevers** [comment]
Just fixed it, that was the issue!

Thanks a lot!

**Comment by LiBa001** [comment]
Alright, then I will need to update the Python version requirements in the docs and README.
